### ISSUE TITLE
SUMMARY: Satisfactory

### ISSUE THREAD

**Issue by jzhu01** [newlandj/prj-rev-bwfs-dasmoto#5]
Great job on this project! I really liked your usage of spans, and how you styled the font-family. In terms of improvement, I recommend removing the font-weight:bold on your h1 and h2s, as well as using IDs instead of classes when selecting the h2s to apply a background color.

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the fantastic work! ^_^

**Comment by newlandj** [comment]
Thanks!
